import { useState, useEffect, useCallback } from 'react';
import {
  useAccount,
  useConnect,
  useDisconnect,
  useWriteContract,
  useWaitForTransactionReceipt,
  useReadContract,
  useChainId,
  useSwitchChain,
  WagmiProvider,
  createConfig,
  http
} from 'wagmi';
import { arbitrumSepolia, foundry } from 'wagmi/chains';
import { injected } from 'wagmi/connectors';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { parseEther } from 'viem';
import {
  Wallet,
  ArrowRightLeft,
  ShieldCheck,
  Vote,
  Coins,
  RefreshCcw,
  LayoutDashboard,
  ExternalLink,
  UserPlus,
  Plus,
  MinusCircle,
  Activity,
  Flame,
  Sparkles,
  UserCheck,
  FileText,
  AlertTriangle,
  Loader2,
  HelpCircle,
  Gem,
  Package,
  Layers,
  Award,
  Zap
} from 'lucide-react';

import GameTokenABI from './constants/GameToken.json';
import GameItemABI from './constants/GameItem.json';
import GameGovernorABI from './constants/GameGovernor.json';
import GameAMMABI from './constants/GameAMM.json';
import RentalVaultABI from './constants/RentalVault.json';

import './index.css';
// Auto-generated by `just sync-addresses` — do not edit manually
import localContracts from './contracts.local.json';

// --- CONFIGURATION ---

const queryClient = new QueryClient();

const config = createConfig({
  chains: [arbitrumSepolia, foundry],
  connectors: [injected()],
  transports: {
    [arbitrumSepolia.id]: http(),
    [foundry.id]: http(),
  },
});


// Dynamic contract mapping per network
const CONTRACT_ADDRESSES = {
  31337: localContracts,  // auto-synced from deployments/local.json
  421614: {
    GameToken: "0x491707829CE7b07227C40A61C781dB6ddDDD3683",
    GameItem: "0xA710612fe06503CBc502Ef5A364b253c804BD3d5",
    GameAMM: "0x2082b95707B5567964be85e75355e96B7b2e408B",
    RentalVault: "0x8d7A7217fb714624c215b9a6925a3c9fdAD94D07",
    GameGovernor: "0x155f0844eC55E454918AE043dDF2f4b976CC1b80",
  }
};

const getContracts = (chainId) => {
  return CONTRACT_ADDRESSES[chainId] || CONTRACT_ADDRESSES[421614]; // fallback to Arb Sepolia
};

// Item resource names
const RESOURCE_ITEMS = [
  { id: 1, name: "Gold Ore", icon: Gem, color: "text-amber-500", desc: "Rare mineral for high-tier crafting." },
  { id: 2, name: "Iron Ore", icon: Layers, color: "text-gray-400", desc: "Basic metal used in armor construction." },
  { id: 3, name: "Copper Ore", icon: Layers, color: "text-orange-500", desc: "Highly conductive mineral." },
  { id: 4, name: "Wood Log", icon: Package, color: "text-amber-700", desc: "Primary resource for general construction." },
  { id: 5, name: "Stone Block", icon: Layers, color: "text-slate-500", desc: "Heavy blocks for fortified structures." },
  { id: 6, name: "Leather Hide", icon: Package, color: "text-yellow-600", desc: "Tanned hide used in flexible gear." },
  { id: 7, name: "Obsidian Shard", icon: Zap, color: "text-purple-600", desc: "Ultra-sharp volcanic glass shard." },
  { id: 8, name: "Mithril Ore", icon: Sparkles, color: "text-cyan-400", desc: "Legendary light & strong alloy material." },
  { id: 9, name: "Dragon Scale", icon: Flame, color: "text-red-500", desc: "Mythical fire-resistant armored plate." },
  { id: 10, name: "Ethereal Dust", icon: HelpCircle, color: "text-pink-400", desc: "Magical essence used in enchantments." }
];

// Helper to format smart contract error messages cleanly
function formatError(error) {
  if (!error) return "";
  const msg = error.shortMessage || error.message || error.toString();
  if (msg.includes("User rejected")) {
    return "Transaction was cancelled by user.";
  }
  if (msg.includes("insufficient funds")) {
    return "Insufficient balance to pay for gas fees.";
  }
  if (msg.includes("Slippage too high")) {
    return "Transaction aborted: slippage protection triggered.";
  }
  if (msg.includes("Cooldown active")) {
    return "Withdrawal locked: Cooldown cooldown still active.";
  }
  return msg.split("\n")[0] || "An unexpected error occurred.";
}

// Safely format a BigInt token amount (18 decimals) to a display string
// without overflowing JS Number precision
function safeFormatEther(raw) {
  if (raw === undefined || raw === null) return "0.00";
  const bigintRaw = BigInt(raw.toString());
  if (bigintRaw === 0n) return "0.00";
  try {
    // Divide by 10^15 first to keep within safe integer range,
    // then divide the remaining 10^3 as a float
    const upper = bigintRaw / 1000000000000000n;
    const display = Number(upper) / 1000;
    if (!isFinite(display)) return "0.00";
    return display.toLocaleString(undefined, { maximumFractionDigits: 2 });
  } catch {
    return "err";
  }
}

// --- MAIN COMPONENTS ---

function ConnectWallet() {
  const { address, isConnected, chain } = useAccount();
  const { connect, connectors, isPending } = useConnect();
  const { disconnect } = useDisconnect();

  if (isConnected) {
    return (
      <div className="flex items-center gap-3">
        <span className="flex items-center gap-2 bg-surface-muted border border-border px-3 py-1.5 rounded-lg text-xs font-semibold shadow-sm text-foreground">
          <span className={`w-2 h-2 rounded-full ${chain?.id === 31337 || chain?.id === 421614 ? "bg-green-500" : "bg-red-500 animate-pulse"}`}></span>
          {chain?.name || "Unknown Chain"}
        </span>
        <span className="flex items-center gap-2 bg-surface-muted text-foreground px-4 py-2 rounded-lg text-sm font-semibold border border-border shadow-sm">
          <Wallet size={16} className="text-muted" />
          {address?.slice(0, 6)}...{address?.slice(-4)}
        </span>
        <button onClick={() => disconnect()} className="btn btn-outline text-xs px-3 py-2">
          Disconnect
        </button>
      </div>
    );
  }

  if (connectors.length === 0) {
    return (
      <div className="p-4 bg-red-50 text-red-600 rounded-xl text-sm font-semibold border border-red-100 flex flex-col items-center gap-2">
        <AlertTriangle size={24} />
        <p>No Web3 Provider Detected.</p>
        <p className="text-xs font-medium text-red-500">Please install MetaMask or another supported wallet to continue.</p>
      </div>
    );
  }

  return (
    <div className="flex justify-center w-full gap-2">
      {connectors.slice(0, 1).map((connector) => (
        <button
          key={connector.uid}
          onClick={() => connect({ connector })}
          disabled={isPending}
          className="btn btn-primary text-sm px-6 py-3 w-full sm:w-auto font-bold shadow-md hover:shadow-lg rounded-xl"
        >
          {isPending ? (
            <>
              <Loader2 size={18} className="animate-spin" /> Connecting...
            </>
          ) : (
            'Connect Wallet'
          )}
        </button>
      ))}
    </div>
  );
} function SwapTab({ contracts }) {
  const { address } = useAccount();
  const [amountIn, setAmountIn] = useState('');
  const [minAmountOut, setMinAmountOut] = useState('0.1');
  const [mode, setMode] = useState('swap'); // 'swap' | 'add-liquidity' | 'remove-liquidity'
  const [addAmountX, setAddAmountX] = useState('');
  const [addAmountY, setAddAmountY] = useState('');
  const [removeShares, setRemoveShares] = useState('');

  const { writeContract, data: hash, isPending, error } = useWriteContract();
  const { isLoading: isConfirming, isSuccess } = useWaitForTransactionReceipt({ hash });

  // 1. Fetch user allowance for GAME (Token X) on AMM
  const { data: allowanceX } = useReadContract({
    address: contracts.GameToken,
    abi: GameTokenABI,
    functionName: 'allowance',
    args: address ? [address, contracts.GameAMM] : undefined,
    query: {
      enabled: !!address,
      refetchInterval: 3000
    }
  });

  // 1.1. Fetch user balance of GAME (Token X)
  const { data: balanceX } = useReadContract({
    address: contracts.GameToken,
    abi: GameTokenABI,
    functionName: 'balanceOf',
    args: address ? [address] : undefined,
    query: {
      enabled: !!address,
      refetchInterval: 3000
    }
  });

  // 2. Fetch the WOOD (Token Y) ERC20 address from GameAMM
  const { data: tokenYAddress } = useReadContract({
    address: contracts.GameAMM,
    abi: GameAMMABI,
    functionName: 'TOKEN_Y',
    query: { enabled: !!address }
  });

  // 3. Fetch user allowance for WOOD (Token Y) on AMM
  const { data: allowanceY } = useReadContract({
    address: tokenYAddress,
    abi: GameTokenABI,
    functionName: 'allowance',
    args: address && tokenYAddress ? [address, contracts.GameAMM] : undefined,
    query: {
      enabled: !!address && !!tokenYAddress,
      refetchInterval: 3000
    }
  });

  // 3.1. Fetch user balance of WOOD (Token Y)
  const { data: balanceY } = useReadContract({
    address: tokenYAddress,
    abi: GameTokenABI,
    functionName: 'balanceOf',
    args: address && tokenYAddress ? [address] : undefined,
    query: {
      enabled: !!address && !!tokenYAddress,
      refetchInterval: 3000
    }
  });

  // 4. Fetch reserve ratio / AMM liquidity details
  const { data: reserveX } = useReadContract({
    address: contracts.GameAMM,
    abi: GameAMMABI,
    functionName: 'reserveX',
    query: {
      enabled: !!address,
      refetchInterval: 3000
    }
  });
  const { data: reserveY } = useReadContract({
    address: contracts.GameAMM,
    abi: GameAMMABI,
    functionName: 'reserveY',
    query: {
      enabled: !!address,
      refetchInterval: 3000
    }
  });

  // 5. Fetch user LP shares balance
  const { data: lpBalance } = useReadContract({
    address: contracts.GameAMM,
    abi: GameAMMABI,
    functionName: 'balanceOf',
    args: address ? [address] : undefined,
    query: {
      enabled: !!address,
      refetchInterval: 3000
    }
  });

  // Determine if swap approval is needed
  const swapAmountWei = amountIn ? parseEther(amountIn) : 0n;
  const balanceXVal = balanceX ?? 0n;
  const balanceYVal = balanceY ?? 0n;

  const hasInsufficientSwapBalance = swapAmountWei > 0n && balanceXVal < swapAmountWei;

  // Determine if AMM pool actually has liquidity reserves
  const hasReserves = reserveX !== undefined && reserveY !== undefined && reserveX > 0n && reserveY > 0n;

  const needsSwapApproval = address && allowanceX !== undefined && swapAmountWei > 0n && allowanceX < swapAmountWei && !hasInsufficientSwapBalance;

  // Determine if liquidity approvals are needed
  const addAmountXWei = addAmountX ? parseEther(addAmountX) : 0n;
  const addAmountYWei = addAmountY ? parseEther(addAmountY) : 0n;

  const hasInsufficientLiquidityBalanceX = addAmountXWei > 0n && balanceXVal < addAmountXWei;
  const hasInsufficientLiquidityBalanceY = addAmountYWei > 0n && balanceYVal < addAmountYWei;

  const needsLiquidityApproveX = address && allowanceX !== undefined && addAmountXWei > 0n && allowanceX < addAmountXWei && !hasInsufficientLiquidityBalanceX;
  const needsLiquidityApproveY = address && allowanceY !== undefined && addAmountYWei > 0n && allowanceY < addAmountYWei && !hasInsufficientLiquidityBalanceY;

  const removeSharesWei = removeShares ? parseEther(removeShares) : 0n;
  const lpBalanceVal = lpBalance ?? 0n;
  const hasInsufficientLpBalance = removeSharesWei > 0n && lpBalanceVal < removeSharesWei;

  // Calculate expected swap output dynamically from AMM pool reserves if available!
  let estimatedAmountOut = "0.0";
  if (hasReserves && amountIn) {
    try {
      const amountInWei = parseEther(amountIn);
      const amountInWithFee = amountInWei * 997n;
      const numerator = amountInWithFee * reserveY;
      const denominator = (reserveX * 1000n) + amountInWithFee;
      const amountOutWei = numerator / denominator;
      const displayRaw = formatEther(amountOutWei);
      const parsed = parseFloat(displayRaw);
      estimatedAmountOut = isNaN(parsed) ? "0.0" : parsed.toFixed(4);
    } catch {
      estimatedAmountOut = "0.0";
    }
  } else if (amountIn) {
    // Fallback simple 1:1 estimate if pool is empty
    estimatedAmountOut = (parseFloat(amountIn) * 0.997).toFixed(4);
  }

  const handleApproveX = (targetContract, amount) => {
    writeContract({
      address: contracts.GameToken,
      abi: GameTokenABI,
      functionName: 'approve',
      args: [targetContract, amount],
    });
  };

  const handleApproveY = (targetContract, amount) => {
    if (!tokenYAddress) return;
    writeContract({
      address: tokenYAddress,
      abi: GameTokenABI,
      functionName: 'approve',
      args: [targetContract, amount],
    });
  };

  const handleSwap = () => {
    if (!amountIn) return;
    writeContract({
      address: contracts.GameAMM,
      abi: GameAMMABI,
      functionName: 'swap',
      args: [contracts.GameToken, parseEther(amountIn), parseEther(minAmountOut || '0')],
    });
  };

  const handleAddLiquidity = () => {
    if (!addAmountX || !addAmountY) return;
    writeContract({
      address: contracts.GameAMM,
      abi: GameAMMABI,
      functionName: 'addLiquidity',
      args: [parseEther(addAmountX), parseEther(addAmountY)],
    });
  };

  const handleRemoveLiquidity = () => {
    if (!removeShares) return;
    writeContract({
      address: contracts.GameAMM,
      abi: GameAMMABI,
      functionName: 'removeLiquidity',
      args: [parseEther(removeShares)],
    });
  };

  const isAmmLoading = address && (!contracts.GameAMM || !contracts.GameToken || tokenYAddress === undefined);

  return (
    <div className="card max-w-lg mx-auto">
      <div className="flex gap-2 mb-6 border-b border-border pb-4">
        <button
          className={`px-3 py-1.5 text-sm font-semibold rounded-lg transition-colors cursor-pointer ${mode === 'swap' ? 'bg-accent text-white' : 'text-muted hover:text-foreground bg-surface-muted'}`}
          onClick={() => setMode('swap')}
        >
          Trade Assets
        </button>
        <button
          className={`px-3 py-1.5 text-sm font-semibold rounded-lg transition-colors cursor-pointer ${mode === 'add-liquidity' ? 'bg-accent text-white' : 'text-muted hover:text-foreground bg-surface-muted'}`}
          onClick={() => setMode('add-liquidity')}
        >
          Supply Liquidity
        </button>
        <button
          className={`px-3 py-1.5 text-sm font-semibold rounded-lg transition-colors cursor-pointer ${mode === 'remove-liquidity' ? 'bg-accent text-white' : 'text-muted hover:text-foreground bg-surface-muted'}`}
          onClick={() => setMode('remove-liquidity')}
        >
          Remove Liquidity
        </button>
      </div>

      {/* Dynamic Pool State/Notice Card */}
      {hasReserves ? (
        <div className="bg-surface-muted/50 rounded-xl p-3 border border-border/60 mb-6 text-center text-xs flex justify-around text-muted">
          <div>
            <span className="font-semibold text-foreground block">{safeFormatEther(reserveX)} GAME</span>
            Pool Reserve X
          </div>
          <div className="border-r border-border/60 my-1"></div>
          <div>
            <span className="font-semibold text-foreground block">{safeFormatEther(reserveY)} WOOD</span>
            Pool Reserve Y
          </div>
        </div>
      ) : (
        <div className="bg-amber-500/10 border border-amber-500/20 text-amber-500 rounded-xl p-3 mb-6 text-xs text-center flex flex-col gap-1">
          <span>⚠️ <strong>Empty Liquidity Pool Notice (Sepolia):</strong></span>
          <span className="opacity-90">Swaps are disabled because there are 0 GAME / 0 WOOD reserves in this L2 pool. You must switch to the <strong>Supply Liquidity</strong> tab to seed the pool ratio first!</span>
        </div>
      )}

      {isAmmLoading ? (
        <div className="text-center py-8 text-muted">Loading AMM contracts and balances...</div>
      ) : (
        <>
          {mode === 'swap' && (
            <div>
              <h2 className="text-xl font-bold mb-1 flex items-center gap-2 text-foreground">
                <ArrowRightLeft size={20} className="text-muted" /> AMM Swap
              </h2>
              <p className="text-muted text-sm mb-6">Swap your Game Tokens for in-game resource materials instantly.</p>

              <div className="input-group mb-4">
                <label className="flex justify-between w-full">
                  <span>You Pay</span>
                  <span className="text-xs font-semibold text-muted">Balance: {safeFormatEther(balanceX)} GAME</span>
                </label>
                <div className="input-with-symbol text-lg">
                  <input
                    type="number"
                    placeholder="0.0"
                    value={amountIn}
                    onChange={(e) => setAmountIn(e.target.value)}
                  />
                  <span className="symbol bg-surface-muted px-2 py-1 rounded-md ml-2 flex items-center gap-1">GAME</span>
                </div>
              </div>

              <div className="flex justify-center -my-2 relative z-10">
                <div className="bg-surface border border-border p-2 rounded-full text-muted shadow-sm hover:text-accent hover:border-accent transition-colors cursor-pointer">
                  <RefreshCcw size={16} />
                </div>
              </div>

              <div className="input-group mt-2 mb-4">
                <label className="flex justify-between w-full">
                  <span>You Receive (Estimated)</span>
                  <span className="text-xs font-semibold text-muted">Balance: {safeFormatEther(balanceY)} WOOD</span>
                </label>
                <div className="input-with-symbol text-lg opacity-80 bg-surface-muted">
                  <input type="text" value={estimatedAmountOut} readOnly className="cursor-not-allowed" />
                  <span className="symbol bg-border px-2 py-1 rounded-md ml-2 flex items-center gap-1">WOOD</span>
                </div>
              </div>

              <div className="input-group mb-4">
                <label>Slippage Protection (Min Output)</label>
                <input
                  type="number"
                  className="w-full bg-background border border-border rounded-lg px-3 py-2 text-sm font-medium outline-none"
                  placeholder="Min amount of output to accept"
                  value={minAmountOut}
                  onChange={(e) => setMinAmountOut(e.target.value)}
                />
              </div>

              {hasInsufficientSwapBalance ? (
                <button className="btn bg-red-600/20 text-red-400 border border-red-500/30 w-full py-3 mt-4 text-base font-bold shadow-lg cursor-not-allowed" disabled={true}>
                  Insufficient GAME Balance
                </button>
              ) : !hasReserves ? (
                <button className="btn bg-red-600/20 text-red-400 border border-red-500/30 w-full py-3 mt-4 text-base font-bold shadow-lg cursor-not-allowed" disabled={true}>
                  AMM Pool is Empty: Please Add Liquidity First
                </button>
              ) : needsSwapApproval ? (
                <button
                  className="btn bg-amber-600 hover:bg-amber-700 text-white w-full py-3 mt-4 text-base font-bold shadow-lg"
                  onClick={() => handleApproveX(contracts.GameAMM, swapAmountWei)}
                  disabled={isPending || isConfirming}
                >
                  {isPending || isConfirming ? 'Approving GAME...' : 'Approve GAME Token'}
                </button>
              ) : (
                <button
                  className="btn btn-primary w-full py-3 mt-4 text-base"
                  onClick={handleSwap}
                  disabled={isPending || isConfirming || !amountIn}
                >
                  {isPending || isConfirming ? 'Processing Swap...' : 'Execute Swap'}
                </button>
              )}
            </div>
          )}

          {mode === 'add-liquidity' && (
            <div>
              <h2 className="text-xl font-bold mb-1 flex items-center gap-2 text-foreground">
                <Plus size={20} className="text-muted" /> Supply Liquidity
              </h2>
              <p className="text-muted text-sm mb-6">Earn trading fees by providing balanced pools of GAME and WOOD resources.</p>

              <div className="input-group mb-4">
                <label className="flex justify-between w-full">
                  <span>GAME Token Amount</span>
                  <span className="text-xs font-semibold text-muted">Balance: {safeFormatEther(balanceX)} GAME</span>
                </label>
                <div className="input-with-symbol text-lg">
                  <input
                    type="number"
                    placeholder="0.0"
                    value={addAmountX}
                    onChange={(e) => setAddAmountX(e.target.value)}
                  />
                  <span className="symbol">GAME</span>
                </div>
              </div>

              <div className="input-group mb-4">
                <label className="flex justify-between w-full">
                  <span>WOOD Resource Amount</span>
                  <span className="text-xs font-semibold text-muted">Balance: {safeFormatEther(balanceY)} WOOD</span>
                </label>
                <div className="input-with-symbol text-lg">
                  <input
                    type="number"
                    placeholder="0.0"
                    value={addAmountY}
                    onChange={(e) => setAddAmountY(e.target.value)}
                  />
                  <span className="symbol">WOOD</span>
                </div>
              </div>

              {hasInsufficientLiquidityBalanceX ? (
                <button className="btn bg-red-600/20 text-red-400 border border-red-500/30 w-full py-3 mt-4 text-base font-bold shadow-lg cursor-not-allowed" disabled={true}>
                  Insufficient GAME Balance (Have: {safeFormatEther(balanceX)})
                </button>
              ) : hasInsufficientLiquidityBalanceY ? (
                <button className="btn bg-red-600/20 text-red-400 border border-red-500/30 w-full py-3 mt-4 text-base font-bold shadow-lg cursor-not-allowed" disabled={true}>
                  Insufficient WOOD Balance (Have: {safeFormatEther(balanceY)})
                </button>
              ) : needsLiquidityApproveX ? (
                <button
                  className="btn bg-amber-600 hover:bg-amber-700 text-white w-full py-3 mt-4 text-base font-bold shadow-lg"
                  onClick={() => handleApproveX(contracts.GameAMM, addAmountXWei)}
                  disabled={isPending || isConfirming}
                >
                  {isPending || isConfirming ? 'Approving GAME...' : 'Approve GAME for Liquidity'}
                </button>
              ) : needsLiquidityApproveY ? (
                <button
                  className="btn bg-amber-600 hover:bg-amber-700 text-white w-full py-3 mt-4 text-base font-bold shadow-lg"
                  onClick={() => handleApproveY(contracts.GameAMM, addAmountYWei)}
                  disabled={isPending || isConfirming}
                >
                  {isPending || isConfirming ? 'Approving WOOD...' : 'Approve WOOD for Liquidity'}
                </button>
              ) : (
                <button
                  className="btn btn-primary w-full py-3 mt-4 text-base"
                  onClick={handleAddLiquidity}
                  disabled={isPending || isConfirming || !addAmountX || !addAmountY}
                >
                  {isPending || isConfirming ? 'Adding Liquidity...' : 'Add Liquidity'}
                </button>
              )}
            </div>
          )}

          {mode === 'remove-liquidity' && (
            <div>
              <h2 className="text-xl font-bold mb-1 flex items-center gap-2 text-foreground">
                <MinusCircle size={20} className="text-muted" /> Burn LP Tokens
              </h2>
              <p className="text-muted text-sm mb-6">Redeem your Liquidity Pool shares back for the underlying token assets.</p>

              <div className="input-group mb-4">
                <label className="flex justify-between w-full">
                  <span>LP Shares to Burn</span>
                  <span className="text-xs font-semibold text-muted">Balance: {safeFormatEther(lpBalance)} GAMM-LP</span>
                </label>
                <div className="input-with-symbol text-lg">
                  <input
                    type="number"
                    placeholder="0.0"
                    value={removeShares}
                    onChange={(e) => setRemoveShares(e.target.value)}
                  />
                  <span className="symbol">GAMM-LP</span>
                </div>
              </div>

              {hasInsufficientLpBalance ? (
                <button className="btn bg-red-600/20 text-red-400 border border-red-500/30 w-full py-3 mt-4 text-base font-bold shadow-lg cursor-not-allowed" disabled={true}>
                  Insufficient LP Shares (Have: {safeFormatEther(lpBalance)})
                </button>
              ) : (
                <button
                  className="btn btn-primary w-full py-3 mt-4 text-base"
                  onClick={handleRemoveLiquidity}
                  disabled={isPending || isConfirming || !removeShares}
                >
                  {isPending || isConfirming ? 'Burning LP Shares...' : 'Remove Liquidity'}
                </button>
              )}
            </div>
          )}
        </>
      )}

      {error && <div className="mt-4 p-3 bg-red-50 text-red-700 border border-red-200 rounded-lg text-center text-sm font-semibold">{formatError(error)}</div>}
      {isSuccess && <div className="status-success">Transaction confirmed successfully!</div>}
    </div>
  );
}

function VaultTab({ contracts }) {
  const { address } = useAccount();
  const [stakeAmount, setStakeAmount] = useState('');
  const [unstakeAmount, setUnstakeAmount] = useState('');
  const [nftAmount, setNftAmount] = useState('');
  const [nftWithdrawShares, setNftWithdrawShares] = useState('');
  const [action, setAction] = useState('stake'); // 'stake' | 'unstake' | 'nft-stake' | 'nft-unstake'

  const { writeContract, data: hash, isPending, error } = useWriteContract();
  const { isLoading: isConfirming, isSuccess } = useWaitForTransactionReceipt({ hash });

  // 1. Fetch user allowance for GAME on RentalVault
  const { data: allowanceVault } = useReadContract({
    address: contracts.GameToken,
    abi: GameTokenABI,
    functionName: 'allowance',
    args: address ? [address, contracts.RentalVault] : undefined,
    query: {
      enabled: !!address,
      refetchInterval: 3000
    }
  });

  // 2. Fetch if user has approved RentalVault for all GameItems (ERC-1155)
  const { data: isApprovedForAll } = useReadContract({
    address: contracts.GameItem,
    abi: GameItemABI,
    functionName: 'isApprovedForAll',
    args: address ? [address, contracts.RentalVault] : undefined,
    query: {
      enabled: !!address,
      refetchInterval: 3000
    }
  });

  // Determine if approvals are needed
  const stakeAmountWei = stakeAmount ? parseEther(stakeAmount) : 0n;
  const needsVaultApprove = address && allowanceVault !== undefined && stakeAmountWei > 0n && allowanceVault < stakeAmountWei;
  const needsNFTApprove = address && isApprovedForAll === false;

  const handleApproveVault = () => {
    writeContract({
      address: contracts.GameToken,
      abi: GameTokenABI,
      functionName: 'approve',
      args: [contracts.RentalVault, stakeAmountWei],
    });
  };

  const handleApproveNFT = () => {
    writeContract({
      address: contracts.GameItem,
      abi: GameItemABI,
      functionName: 'setApprovalForAll',
      args: [contracts.RentalVault, true],
    });
  };

  const handleDeposit = () => {
    if (!stakeAmount || !address) return;
    writeContract({
      address: contracts.RentalVault,
      abi: RentalVaultABI,
      functionName: 'deposit',
      args: [parseEther(stakeAmount), address],
    });
  };

  const handleWithdraw = () => {
    if (!unstakeAmount || !address) return;
    writeContract({
      address: contracts.RentalVault,
      abi: RentalVaultABI,
      functionName: 'withdraw',
      args: [parseEther(unstakeAmount), address, address],
    });
  };

  const handleDepositNFT = () => {
    if (!nftAmount) return;
    writeContract({
      address: contracts.RentalVault,
      abi: RentalVaultABI,
      functionName: 'depositNFT',
      args: [BigInt(nftAmount)],
    });
  };

  const handleWithdrawNFT = () => {
    if (!nftWithdrawShares) return;
    writeContract({
      address: contracts.RentalVault,
      abi: RentalVaultABI,
      functionName: 'withdrawNFT',
      args: [parseEther(nftWithdrawShares)],
    });
  };

  return (
    <div className="card max-w-lg mx-auto">
      <div className="flex gap-2 mb-6 border-b border-border pb-4">
        <button
          className={`px-3 py-1.5 text-sm font-semibold rounded-lg transition-colors cursor-pointer ${action === 'stake' ? 'bg-accent text-white' : 'text-muted hover:text-foreground bg-surface-muted'}`}
          onClick={() => setAction('stake')}
        >
          Stake Assets
        </button>
        <button
          className={`px-3 py-1.5 text-sm font-semibold rounded-lg transition-colors cursor-pointer ${action === 'unstake' ? 'bg-accent text-white' : 'text-muted hover:text-foreground bg-surface-muted'}`}
          onClick={() => setAction('unstake')}
        >
          Unstake
        </button>
        <button
          className={`px-3 py-1.5 text-sm font-semibold rounded-lg transition-colors cursor-pointer ${action === 'nft-stake' ? 'bg-accent text-white' : 'text-muted hover:text-foreground bg-surface-muted'}`}
          onClick={() => setAction('nft-stake')}
        >
          Stake NFT
        </button>
        <button
          className={`px-3 py-1.5 text-sm font-semibold rounded-lg transition-colors cursor-pointer ${action === 'nft-unstake' ? 'bg-accent text-white' : 'text-muted hover:text-foreground bg-surface-muted'}`}
          onClick={() => setAction('nft-unstake')}
        >
          Redeem NFT
        </button>
      </div>

      {action === 'stake' && (
        <div>
          <h2 className="text-xl font-bold mb-1 flex items-center gap-2 text-foreground">
            <ShieldCheck size={20} className="text-muted" /> Stake GAME
          </h2>
          <p className="text-muted text-sm mb-6">Lock your fungible GAME tokens in the secure vault to compound rewards.</p>

          <div className="input-group mb-4">
            <label>Amount to Stake</label>
            <div className="input-with-symbol text-lg">
              <input
                type="number"
                placeholder="0.0"
                value={stakeAmount}
                onChange={(e) => setStakeAmount(e.target.value)}
              />
              <span className="symbol">GAME</span>
            </div>
          </div>

          {needsVaultApprove ? (
            <button
              className="btn bg-amber-600 hover:bg-amber-700 text-white w-full py-3 mt-4 text-base font-bold shadow-lg"
              onClick={handleApproveVault}
              disabled={isPending || isConfirming}
            >
              {isPending || isConfirming ? 'Approving GAME...' : 'Approve GAME for Vault'}
            </button>
          ) : (
            <button
              className="btn btn-primary w-full py-3 mt-4 text-base"
              onClick={handleDeposit}
              disabled={isPending || isConfirming || !stakeAmount}
            >
              {isPending || isConfirming ? 'Processing Deposit...' : 'Confirm Staking'}
            </button>
          )}
        </div>
      )}

      {action === 'unstake' && (
        <div>
          <h2 className="text-xl font-bold mb-1 flex items-center gap-2 text-foreground">
            <MinusCircle size={20} className="text-muted" /> Withdraw GAME
          </h2>
          <p className="text-muted text-sm mb-6">Unlock and withdraw staked GAME and any accrued interest balance.</p>

          <div className="input-group mb-4">
            <label>Amount to Withdraw</label>
            <div className="input-with-symbol text-lg">
              <input
                type="number"
                placeholder="0.0"
                value={unstakeAmount}
                onChange={(e) => setUnstakeAmount(e.target.value)}
              />
              <span className="symbol">GAME</span>
            </div>
          </div>

          <button
            className="btn btn-primary w-full py-3 mt-4 text-base"
            onClick={handleWithdraw}
            disabled={isPending || isConfirming || !unstakeAmount}
          >
            {isPending || isConfirming ? 'Processing Withdrawal...' : 'Withdraw Assets'}
          </button>
        </div>
      )}

      {action === 'nft-stake' && (
        <div>
          <h2 className="text-xl font-bold mb-1 flex items-center gap-2 text-foreground">
            <Sparkles size={20} className="text-muted" /> Deposit Item NFT
          </h2>
          <p className="text-muted text-sm mb-6">Stake unique resource NFTs (ID 1) directly in the vault to capture premium yield boosting.</p>

          <div className="input-group mb-4">
            <label>NFT Quantity (ID: 1)</label>
            <div className="input-with-symbol text-lg">
              <input
                type="number"
                placeholder="0"
                value={nftAmount}
                onChange={(e) => setNftAmount(e.target.value)}
              />
              <span className="symbol">Items</span>
            </div>
          </div>

          {needsNFTApprove ? (
            <button
              className="btn bg-amber-600 hover:bg-amber-700 text-white w-full py-3 mt-4 text-base font-bold shadow-lg"
              onClick={handleApproveNFT}
              disabled={isPending || isConfirming}
            >
              {isPending || isConfirming ? 'Approving NFTs...' : 'Approve NFTs for Vault'}
            </button>
          ) : (
            <button
              className="btn btn-primary w-full py-3 mt-4 text-base"
              onClick={handleDepositNFT}
              disabled={isPending || isConfirming || !nftAmount}
            >
              {isPending || isConfirming ? 'Staking NFT...' : 'Deposit NFT'}
            </button>
          )}
        </div>
      )}

      {action === 'nft-unstake' && (
        <div>
          <h2 className="text-xl font-bold mb-1 flex items-center gap-2 text-foreground">
            <MinusCircle size={20} className="text-muted" /> Redeem Staked NFT
          </h2>
          <p className="text-muted text-sm mb-6">Redeem your vault shares back for the deposited item NFT assets.</p>

          <div className="input-group mb-4">
            <label>Vault Share Amount</label>
            <div className="input-with-symbol text-lg">
              <input
                type="number"
                placeholder="0.0"
                value={nftWithdrawShares}
                onChange={(e) => setNftWithdrawShares(e.target.value)}
              />
              <span className="symbol">Shares</span>
            </div>
          </div>

          <button
            className="btn btn-primary w-full py-3 mt-4 text-base"
            onClick={handleWithdrawNFT}
            disabled={isPending || isConfirming || !nftWithdrawShares}
          >
            {isPending || isConfirming ? 'Redeeming NFT...' : 'Withdraw NFT'}
          </button>
        </div>
      )}

      {error && <div className="mt-4 p-3 bg-red-50 text-red-700 border border-red-200 rounded-lg text-center text-sm font-semibold">{formatError(error)}</div>}
      {isSuccess && <div className="status-success">Vault Transaction confirmed successfully!</div>}
    </div>
  );
}

function GovernanceTab({ contracts }) {
  useAccount();
  const [delegatee, setDelegatee] = useState('');
  const [proposalTargets, setProposalTargets] = useState('');
  const [proposalValues, setProposalValues] = useState('0');
  const [proposalCalldatas, setProposalCalldatas] = useState('');
  const [proposalDesc, setProposalDesc] = useState('');
  const [actionTab, setActionTab] = useState('proposals'); // 'proposals' | 'delegate' | 'create-proposal'
  const [manualProposalId, setManualProposalId] = useState('');

  // Subgraph Integration State & Fetcher
  const [subgraphUrl, setSubgraphUrl] = useState(() => {
    return localStorage.getItem('gamefi_subgraph_url') || import.meta.env.VITE_SUBGRAPH_URL || 'https://api.studio.thegraph.com/query/99999/gamefi-protocol/v0.0.1';
  });
  const [subgraphProposals, setSubgraphProposals] = useState([]);
  const [isLoadingSubgraph, setIsLoadingSubgraph] = useState(false);
  const [subgraphError, setSubgraphError] = useState(null);

  const fetchFromSubgraph = useCallback(async (url) => {
    const urlToUse = url || subgraphUrl;
    if (!urlToUse || urlToUse.includes('99999')) {
      setSubgraphError('Please configure your Graph Studio Subgraph Query URL below.');
      return;
    }
    setIsLoadingSubgraph(true);
    setSubgraphError(null);
    try {
      const query = `
        query {
          proposals(orderBy: startBlock, orderDirection: desc, first: 10) {
            id
            proposer
            description
            status
            startBlock
            endBlock
          }
        }
      `;
      const response = await fetch(urlToUse, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ query }),
      });
      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }
      const resData = await response.json();
      if (resData.errors) {
        throw new Error(resData.errors[0].message);
      }
      const data = resData.data?.proposals || [];
      setSubgraphProposals(data);
      localStorage.setItem('gamefi_subgraph_url', urlToUse);
    } catch (err) {
      setSubgraphError(err.message || 'Failed to fetch from subgraph');
      setSubgraphProposals([]);
    } finally {
      setIsLoadingSubgraph(false);
    }
  }, [subgraphUrl]);

  useEffect(() => {
    const storedUrl = localStorage.getItem('gamefi_subgraph_url') || import.meta.env.VITE_SUBGRAPH_URL;
    if (storedUrl && !storedUrl.includes('99999')) {
      // Defer execution to satisfy set-state-in-effect ESLint rules
      const timer = setTimeout(() => {
        fetchFromSubgraph(storedUrl);
      }, 0);
      return () => clearTimeout(timer);
    }
  }, [fetchFromSubgraph]);

  const { writeContract, data: hash, isPending, error } = useWriteContract();
  const { isLoading: isConfirming, isSuccess } = useWaitForTransactionReceipt({ hash });

  const handleDelegate = () => {
    if (!delegatee) return;
    writeContract({
      address: contracts.GameToken,
      abi: GameTokenABI,
      functionName: 'delegate',
      args: [delegatee],
    });
  };

  const handleCreateProposal = () => {
    if (!proposalTargets || !proposalDesc) return;
    // Format simple proposal
    writeContract({
      address: contracts.GameGovernor,
      abi: GameGovernorABI,
      functionName: 'propose',
      args: [
        [proposalTargets],
        [BigInt(proposalValues || '0')],
        [proposalCalldatas || '0x'],
        proposalDesc
      ],
    });
  };

  const castVoteOnProposal = (proposalId, support) => {
    writeContract({
      address: contracts.GameGovernor,
      abi: GameGovernorABI,
      functionName: 'castVote',
      args: [BigInt(proposalId), support],
    });
  };

  const handleManualVote = (support) => {
    if (!manualProposalId) return;
    try {
      // Allow hex prefixed or regular base 10 proposal IDs
      const cleanId = manualProposalId.trim();
      const formattedId = BigInt(cleanId);
      writeContract({
        address: contracts.GameGovernor,
        abi: GameGovernorABI,
        functionName: 'castVote',
        args: [formattedId, support],
      });
    } catch (err) {
      alert("Invalid Proposal ID format. Make sure it is a valid hex hash or decimal integer.");
    }
  };

  return (
    <div className="card">
      <div className="flex gap-2 mb-6 border-b border-border pb-4">
        <button
          className={`px-3 py-1.5 text-sm font-semibold rounded-lg transition-colors cursor-pointer ${actionTab === 'proposals' ? 'bg-accent text-white' : 'text-muted hover:text-foreground bg-surface-muted'}`}
          onClick={() => setActionTab('proposals')}
        >
          Proposals List
        </button>
        <button
          className={`px-3 py-1.5 text-sm font-semibold rounded-lg transition-colors cursor-pointer ${actionTab === 'delegate' ? 'bg-accent text-white' : 'text-muted hover:text-foreground bg-surface-muted'}`}
          onClick={() => setActionTab('delegate')}
        >
          Delegate Power
        </button>
        <button
          className={`px-3 py-1.5 text-sm font-semibold rounded-lg transition-colors cursor-pointer ${actionTab === 'create-proposal' ? 'bg-accent text-white' : 'text-muted hover:text-foreground bg-surface-muted'}`}
          onClick={() => setActionTab('create-proposal')}
        >
          Submit Proposal
        </button>
      </div>

      {actionTab === 'proposals' && (
        <div>
          {/* Subgraph Integration settings console */}
          <div className="mb-8 p-6 bg-surface-muted border border-border rounded-2xl shadow-inner relative overflow-hidden">
            <div className="absolute top-0 right-0 p-2 opacity-5">
              <Activity size={96} className="text-accent" />
            </div>
            <h3 className="text-sm font-bold text-accent uppercase tracking-wider mb-2 flex items-center gap-1.5">
              <Sparkles size={16} /> Subgraph Indexer Console
            </h3>
            <p className="text-xs text-muted leading-relaxed mb-4">
              Query state values, crafting parameters, and voting histories directly from **The Graph Decentralized Indexing Network** instead of performing costly direct on-chain RPC reads.
            </p>
            <div className="flex flex-col sm:flex-row gap-2">
              <input
                type="text"
                placeholder="Enter Graph Studio Query URL (https://api.studio.thegraph.com/query/...)"
                value={subgraphUrl}
                onChange={(e) => setSubgraphUrl(e.target.value)}
                className="flex-1 bg-background text-foreground border border-border px-3.5 py-2 rounded-xl text-xs outline-none font-mono focus:border-accent transition-colors"
              />
              <button
                onClick={() => fetchFromSubgraph(subgraphUrl)}
                className="btn btn-primary text-xs py-2 px-4 font-semibold shrink-0 cursor-pointer shadow-md rounded-xl hover:shadow-lg transition-all"
                disabled={isLoadingSubgraph}
              >
                {isLoadingSubgraph ? (
                  <span className="flex items-center gap-1">
                    <Loader2 size={12} className="animate-spin" /> Querying...
                  </span>
                ) : (
                  "Query Indexer"
                )}
              </button>
            </div>
            {subgraphError && (
              <p className="text-[11px] text-amber-600 font-semibold mt-2.5 flex items-center gap-1">
                <AlertTriangle size={12} /> {subgraphError}
              </p>
            )}
          </div>

          <h2 className="text-xl font-bold mb-1 flex items-center gap-2 text-foreground">
            <Vote size={20} className="text-muted" /> Active Protocol Proposals
          </h2>
          <p className="text-muted text-sm mb-6">Vote on critical system values, crafting equations, and resource allocation.</p>

          <div className="space-y-6">
            {subgraphProposals.length > 0 ? (
              subgraphProposals.map((prop) => (
                <div
                  key={prop.id}
                  className="p-5 border border-border rounded-xl hover:shadow-md transition-all bg-surface relative overflow-hidden"
                >
                  <div className="absolute top-0 right-0 bg-accent text-white text-[10px] uppercase font-bold px-3 py-1 rounded-bl">
                    Proposal #{prop.id.slice(0, 6)}...
                  </div>
                  <div className="flex justify-between items-start mb-2">
                    <div>
                      <span className={`badge mb-2 uppercase text-[10px] ${prop.status === "Pending" ? "badge-queued" : prop.status === "Active" ? "badge-active" : "badge-queued"}`}>
                        {prop.status}
                      </span>
                      <h3 className="text-lg font-bold text-foreground mt-1">
                        {prop.description || "Unnamed Proposal"}
                      </h3>
                      <p className="text-[11px] text-muted font-mono mt-1">
                        Proposer: {prop.proposer.slice(0, 6)}...{prop.proposer.slice(-4)}
                      </p>
                    </div>
                    <span className="text-xs text-muted font-medium">
                      Blocks: {prop.startBlock} to {prop.endBlock}
                    </span>
                  </div>

                  <div className="flex gap-3 border-t border-border pt-4 mt-4">
                    <button
                      onClick={() => castVoteOnProposal(prop.id, 1)}
                      className="btn btn-primary flex-1 py-2 text-sm font-semibold"
                      disabled={isPending || isConfirming}
                    >
                      Vote For
                    </button>
                    <button
                      onClick={() => castVoteOnProposal(prop.id, 0)}
                      className="btn btn-outline flex-1 py-2 text-sm font-semibold"
                      disabled={isPending || isConfirming}
                    >
                      Vote Against
                    </button>
                  </div>
                </div>
              ))
            ) : (
              <>
                <div className="p-4 bg-amber-500/10 border border-amber-500/30 text-amber-500 rounded-xl text-sm leading-relaxed mb-4">
                  <strong>⚠️ Demo Proposals Active:</strong> These cards represent offline mocked proposals because your custom subgraph is not currently configured/active. Clicking the vote buttons on these cards directly will call the contract with a mock ID of "12" and revert (which causes the high gas fee error). To vote on your actual live on-chain proposals, use the <strong>Manual Vote</strong> panel below.
                </div>

                <div className="p-5 border border-border rounded-xl hover:shadow-md transition-shadow bg-surface relative overflow-hidden">
                  <div className="absolute top-0 right-0 bg-accent text-white text-[10px] uppercase font-bold px-3 py-1 rounded-bl">
                    SIP-12
                  </div>
                  <div className="flex justify-between items-start mb-2">
                    <div>
                      <span className="badge badge-active mb-2">Active</span>
                      <h3 className="text-lg font-bold text-foreground">Update Crafting Costs</h3>
                    </div>
                    <span className="text-xs text-muted font-medium">Ends in 2 days</span>
                  </div>
                  <p className="text-muted mb-5 text-sm">Reduce the crafting resource requirement of high-tier swords by 15% to maintain balanced early-game progression.</p>

                  <div className="flex gap-3 border-t border-border pt-4">
                    <button
                      onClick={() => castVoteOnProposal("12", 1)}
                      className="btn btn-primary flex-1 py-2.5 text-sm font-semibold opacity-60 cursor-not-allowed"
                      disabled={true}
                    >
                      Vote For (Mock)
                    </button>
                    <button
                      onClick={() => castVoteOnProposal("12", 0)}
                      className="btn btn-outline flex-1 py-2.5 text-sm font-semibold opacity-60 cursor-not-allowed"
                      disabled={true}
                    >
                      Vote Against (Mock)
                    </button>
                  </div>
                </div>

                <div className="p-5 border border-border rounded-xl bg-surface-muted opacity-75 relative">
                  <div className="absolute top-0 right-0 bg-gray-400 text-white text-[10px] uppercase font-bold px-3 py-1 rounded-bl">
                    SIP-11
                  </div>
                  <div className="flex justify-between items-start mb-2">
                    <div>
                      <span className="badge badge-queued mb-2">Queued</span>
                      <h3 className="text-lg font-bold text-slate-700">Mithril Plate Armor Blueprint</h3>
                    </div>
                    <span className="text-xs text-muted font-medium">Ready to Execute</span>
                  </div>
                  <p className="text-muted mb-4 text-sm">Add recipe blueprint #104: Allows crafting Level 4 protective plate body pieces.</p>
                  <div className="pt-2">
                    <div className="h-2 w-full bg-border rounded-full overflow-hidden">
                      <div className="h-full bg-green-500 w-[91%]"></div>
                    </div>
                    <div className="flex justify-between text-[11px] font-semibold text-muted mt-2">
                      <span>91% SUPPORT (FOR)</span>
                      <span>9% OPPOSE (AGAINST)</span>
                    </div>
                  </div>
                </div>
              </>
            )}

            {/* Manual Voting Fallback Form */}
            <div className="mt-8 p-6 bg-surface border border-dashed border-border rounded-2xl relative overflow-hidden">
              <h3 className="text-base font-bold text-foreground mb-1.5 flex items-center gap-2">
                <Vote size={18} className="text-accent" /> Direct On-Chain Vote
              </h3>
              <p className="text-xs text-muted mb-5">
                Pasting the actual 256-bit Proposal ID hash below allows you to interact directly with the <strong>GameGovernor</strong> smart contract on Arbitrum Sepolia, completely bypassing any Graph indexer delays!
              </p>
              <div className="flex flex-col gap-4">
                <div className="input-group">
                  <label className="text-xs font-semibold text-muted uppercase tracking-wider mb-1.5 block">Proposal ID (Decimal or Hex)</label>
                  <input
                    type="text"
                    placeholder="e.g. 0x37b868e22bf12e9f71398fc98b6363083aa9be91913b7d138f79e2a75af91744"
                    value={manualProposalId}
                    onChange={(e) => setManualProposalId(e.target.value)}
                    className="w-full bg-background border border-border rounded-xl px-4 py-3 text-sm font-medium outline-none focus:border-accent transition-colors font-mono"
                  />
                </div>
                <div className="flex gap-3">
                  <button
                    onClick={() => handleManualVote(1)}
                    className="btn btn-primary flex-1 py-3 text-sm font-semibold"
                    disabled={isPending || isConfirming || !manualProposalId}
                  >
                    Vote FOR (On-Chain)
                  </button>
                  <button
                    onClick={() => handleManualVote(0)}
                    className="btn btn-outline flex-1 py-3 text-sm font-semibold"
                    disabled={isPending || isConfirming || !manualProposalId}
                  >
                    Vote AGAINST (On-Chain)
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}

      {actionTab === 'delegate' && (
        <div>
          <h2 className="text-xl font-bold mb-1 flex items-center gap-2 text-foreground">
            <UserPlus size={20} className="text-muted" /> Delegate Voting Weight
          </h2>
          <p className="text-muted text-sm mb-6">Assign your voting weight to a proxy address, or back to yourself to restore direct votes.</p>

          <div className="input-group mb-4">
            <label>Delegatee Ethereum Address</label>
            <div className="input-with-symbol text-lg">
              <input
                type="text"
                placeholder="0x..."
                value={delegatee}
                onChange={(e) => setDelegatee(e.target.value)}
              />
              <span className="symbol"><UserCheck size={18} /></span>
            </div>
          </div>

          <button
            className="btn btn-primary w-full py-3 mt-4 text-base"
            onClick={handleDelegate}
            disabled={isPending || isConfirming || !delegatee}
          >
            {isPending || isConfirming ? 'Delegating Power...' : 'Confirm Delegation'}
          </button>
        </div>
      )}

      {actionTab === 'create-proposal' && (
        <div>
          <h2 className="text-xl font-bold mb-1 flex items-center gap-2 text-foreground">
            <FileText size={20} className="text-muted" /> Draft Governance Proposal
          </h2>
          <p className="text-muted text-sm mb-6">Propose on-chain transactions to be executed via the Timelock Controller.</p>

          <div className="input-group mb-4">
            <label>Target Contract Address</label>
            <input
              type="text"
              className="w-full bg-background border border-border rounded-lg px-3 py-2 text-sm outline-none"
              placeholder="0x..."
              value={proposalTargets}
              onChange={(e) => setProposalTargets(e.target.value)}
            />
          </div>

          <div className="input-group mb-4">
            <label>Value (Wei)</label>
            <input
              type="number"
              className="w-full bg-background border border-border rounded-lg px-3 py-2 text-sm outline-none"
              placeholder="0"
              value={proposalValues}
              onChange={(e) => setProposalValues(e.target.value)}
            />
          </div>

          <div className="input-group mb-4">
            <label>Calldata (Hex)</label>
            <input
              type="text"
              className="w-full bg-background border border-border rounded-lg px-3 py-2 text-sm outline-none"
              placeholder="0x..."
              value={proposalCalldatas}
              onChange={(e) => setProposalCalldatas(e.target.value)}
            />
          </div>

          <div className="input-group mb-4">
            <label>Proposal Title & Rationale</label>
            <textarea
              className="w-full bg-background border border-border rounded-lg px-3 py-2 text-sm outline-none h-24 resize-none"
              placeholder="Describe your proposal..."
              value={proposalDesc}
              onChange={(e) => setProposalDesc(e.target.value)}
            />
          </div>

          <button
            className="btn btn-primary w-full py-3 mt-4 text-base"
            onClick={handleCreateProposal}
            disabled={isPending || isConfirming || !proposalTargets || !proposalDesc}
          >
            {isPending || isConfirming ? 'Submitting Proposal...' : 'Submit to Governor'}
          </button>
        </div>
      )}

      {error && <div className="mt-4 p-3 bg-red-50 text-red-700 border border-red-200 rounded-lg text-center text-sm font-semibold">{formatError(error)}</div>}
      {isSuccess && <div className="status-success">Governance action initiated successfully!</div>}
    </div>
  );
}

function InventoryTab({ itemsData }) {
  return (
    <div className="card">
      <h2 className="text-xl font-bold mb-1 flex items-center gap-2 text-foreground">
        <Layers size={20} className="text-muted" /> My Resource Inventory
      </h2>
      <p className="text-muted text-sm mb-6">Real-time balances of crafting materials dynamically indexed from the ERC-1155 contract.</p>

      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-4">
        {RESOURCE_ITEMS.map((item, idx) => {
          const rawBalance = itemsData ? itemsData[idx] : 0n;
          // Resource quantities are in 18 decimals in constructor
          // Safe format: avoids Number precision overflow for huge balances
          let formatted = "0";
          try {
            if (rawBalance && rawBalance > 0n) {
              const upper = rawBalance / 1000000000000000n;
              const display = Number(upper) / 1000;
              formatted = isFinite(display)
                ? display.toLocaleString(undefined, { maximumFractionDigits: 2 })
                : "0";
            }
          } catch { formatted = "0"; }
          const IconComp = item.icon;

          return (
            <div key={item.id} className="p-4 border border-border rounded-xl hover:shadow-md transition-all flex flex-col justify-between bg-surface">
              <div>
                <div className="flex justify-between items-start mb-2">
                  <span className={`p-2 rounded-lg bg-surface-muted border border-border shadow-inner ${item.color}`}>
                    <IconComp size={18} />
                  </span>
                  <span className="text-[10px] text-muted font-bold">ID: {item.id}</span>
                </div>
                <h3 className="font-bold text-foreground text-sm">{item.name}</h3>
                <p className="text-xs text-muted leading-tight mt-1 mb-4 h-12 overflow-hidden">{item.desc}</p>
              </div>
              <div className="text-lg font-extrabold text-foreground border-t border-slate-50 pt-2 flex items-baseline gap-1">
                {formatted}
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}

function Dashboard({ itemsData, contracts }) {
  const { address } = useAccount();

  // 1. Fetch native GAME token balance
  const { data: tokenBal } = useReadContract({
    address: contracts.GameToken,
    abi: GameTokenABI,
    functionName: 'balanceOf',
    args: address ? [address] : undefined,
    query: {
      enabled: !!address,
      refetchInterval: 3000
    }
  });

  // 2. Fetch Staked shares in Rental Vault
  const { data: vaultShares } = useReadContract({
    address: contracts.RentalVault,
    abi: RentalVaultABI,
    functionName: 'balanceOf',
    args: address ? [address] : undefined,
    query: {
      enabled: !!address,
      refetchInterval: 3000
    }
  });

  // 3. Fetch active voting power
  const { data: votesPower } = useReadContract({
    address: contracts.GameToken,
    abi: GameTokenABI,
    functionName: 'getVotes',
    args: address ? [address] : undefined,
    query: {
      enabled: !!address,
      refetchInterval: 3000
    }
  });

  // 4. Fetch current delegate address
  const { data: currentDelegate } = useReadContract({
    address: contracts.GameToken,
    abi: GameTokenABI,
    functionName: 'delegates',
    args: address ? [address] : undefined,
    query: {
      enabled: !!address,
      refetchInterval: 3000
    }
  });

  // 5. Fetch reserve ratio / AMM liquidity details
  const { data: reserveX } = useReadContract({
    address: contracts.GameAMM,
    abi: GameAMMABI,
    functionName: 'reserveX',
    query: {
      enabled: !!address,
      refetchInterval: 3000
    }
  });
  const { data: reserveY } = useReadContract({
    address: contracts.GameAMM,
    abi: GameAMMABI,
    functionName: 'reserveY',
    query: {
      enabled: !!address,
      refetchInterval: 3000
    }
  });


  const totalNftsCount = itemsData
    ? itemsData.reduce((acc, curr) => {
      try { return acc + (curr ?? 0n); } catch { return acc; }
    }, 0n)
    : 0n;

  const nftBalanceFormatted = safeFormatEther(totalNftsCount);

  return (
    <div className="mb-8">
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        <div className="card flex flex-col justify-center">
          <div className="flex items-center gap-2 text-xs font-semibold text-muted uppercase tracking-wider mb-2 whitespace-nowrap">
            <Coins size={16} className="text-muted" /> Wallet Balance
          </div>
          <div className="text-3xl font-extrabold text-foreground tracking-tight">
            {safeFormatEther(tokenBal)}
            <span className="text-sm text-muted font-semibold ml-1">GAME</span>
          </div>
        </div>

        <div className="card flex flex-col justify-center">
          <div className="flex items-center gap-2 text-xs font-semibold text-muted uppercase tracking-wider mb-2 whitespace-nowrap">
            <LayoutDashboard size={16} className="text-muted" /> Staked In Vault
          </div>
          <div className="text-3xl font-extrabold text-foreground tracking-tight">
            {safeFormatEther(vaultShares)}
            <span className="text-sm text-muted font-semibold ml-1">Shares</span>
          </div>
        </div>

        <div className="card flex flex-col justify-center">
          <div className="flex items-center gap-2 text-xs font-semibold text-muted uppercase tracking-wider mb-2 whitespace-nowrap">
            <Award size={16} className="text-muted" /> Voting Power
          </div>
          <div className="text-3xl font-extrabold text-foreground tracking-tight">
            {safeFormatEther(votesPower)}
            <span className="text-sm text-muted font-semibold ml-1">Votes</span>
          </div>
          <div className="text-[10px] text-muted font-semibold mt-1 truncate">
            Delegate: {currentDelegate === "0x0000000000000000000000000000000000000000" ? "None" : `${currentDelegate?.slice(0, 6)}...${currentDelegate?.slice(-4)}`}
          </div>
        </div>

        <div className="card flex flex-col justify-center">
          <div className="flex items-center gap-2 text-xs font-semibold text-muted uppercase tracking-wider mb-2 whitespace-nowrap">
            <Sparkles size={16} className="text-muted" /> Items Owned
          </div>
          <div className="text-3xl font-extrabold text-foreground tracking-tight">
            {nftBalanceFormatted} <span className="text-sm text-muted font-semibold ml-1">Materials</span>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mt-4">
        <div className="card text-xs flex justify-between items-center py-3 px-5">
          <span className="font-semibold text-muted">AMM Pool Balance:</span>
          <span className="font-bold text-foreground">
            {(() => { try { if (!reserveX || reserveX === 0n) return '0'; const v = Number(reserveX / 1000000000000000n) / 1000; return isFinite(v) ? v.toLocaleString(undefined, { maximumFractionDigits: 0 }) : '0'; } catch { return '0'; } })()} GAME / {(() => { try { if (!reserveY || reserveY === 0n) return '0'; const v = Number(reserveY / 1000000000000000n) / 1000; return isFinite(v) ? v.toLocaleString(undefined, { maximumFractionDigits: 0 }) : '0'; } catch { return '0'; } })()}
          </span>
        </div>
        <div className="card text-xs flex justify-between items-center py-3 px-5">
          <span className="font-semibold text-muted">Active Price Oracle:</span>
          <span className="font-bold text-foreground flex items-center gap-1">
            <Activity size={12} className="text-green-500 animate-pulse" /> Chainlink Verified
          </span>
        </div>
      </div>
    </div>
  );
}

function AppContent() {
  const [activeTab, setActiveTab] = useState('swap');
  const { address, isConnected } = useAccount();
  const activeChainId = useChainId();
  const { switchChain } = useSwitchChain();

  const currentContracts = getContracts(activeChainId);

  // Wrong chain check
  const isWrongChain = isConnected && activeChainId !== 31337 && activeChainId !== 421614;

  // Fetch dynamic user inventory balances via balanceOfBatch
  const { data: itemsData } = useReadContract({
    address: currentContracts.GameItem,
    abi: GameItemABI,
    functionName: 'balanceOfBatch',
    args: address ? [
      Array(10).fill(address),
      [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    ] : undefined,
    query: {
      enabled: !!address,
      refetchInterval: 3000 // refetch every 3 seconds
    }
  });

  if (!isConnected) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-background px-4">
        <div className="bg-surface pt-12 pb-12 px-8 md:px-14 rounded-3xl text-center max-w-lg shadow-xl border border-border flex flex-col items-center">
          <div className="flex justify-center mb-8">
            <div className="p-5 bg-accent rounded-2xl shadow-sm">
              <ShieldCheck color="#ffffff" size={52} />
            </div>
          </div>
          <h1 className="text-4xl font-extrabold mb-5 text-foreground tracking-tight">GameFi Protocol</h1>
          <p className="mb-8 text-muted text-lg leading-relaxed">The high-performance, decentralized gaming economy. Instantly swap resources, stake items to yield GRS, and exercise democratic voting power.</p>
          <div className="w-full flex justify-center">
            <ConnectWallet />
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-background text-foreground flex flex-col">
      {/* Network Alert Banner */}
      {isWrongChain && (
        <div className="bg-amber-50 border-b border-amber-200 text-amber-800 px-6 py-3 flex flex-col sm:flex-row items-center justify-between gap-3 text-sm font-semibold">
          <span className="flex items-center gap-2">
            <AlertTriangle size={18} className="text-amber-600 shrink-0" />
            Wrong Network: The protocol operates on Foundry Local (31337) or Arbitrum Sepolia (421614).
          </span>
          <div className="flex gap-2">
            <button
              onClick={() => switchChain({ chainId: 31337 })}
              className="px-3 py-1 bg-amber-800 text-white rounded text-xs hover:bg-amber-900 cursor-pointer"
            >
              Switch to Foundry
            </button>
            <button
              onClick={() => switchChain({ chainId: 421614 })}
              className="px-3 py-1 bg-amber-800 text-white rounded text-xs hover:bg-amber-900 cursor-pointer"
            >
              Switch to Arbitrum Sepolia
            </button>
          </div>
        </div>
      )}

      <header className="flex flex-col md:flex-row justify-between items-center py-4 px-6 md:px-12 bg-surface border-b border-border sticky top-0 z-50 gap-4">
        <div className="flex items-center gap-3 font-extrabold text-xl text-accent tracking-tight">
          <ShieldCheck size={28} />
          <span>GameFi Protocol</span>
          <span className="text-[10px] font-bold text-muted bg-surface-muted border border-border px-2 py-0.5 rounded-full uppercase">
            {activeChainId === 31337 ? "Local Anvil" : "Testnet Dev"}
          </span>
        </div>
        <ConnectWallet />
      </header>

      <main className="max-w-6xl mx-auto w-full p-4 md:p-8 flex-1">
        <Dashboard itemsData={itemsData} contracts={currentContracts} />

        <div className="flex gap-2 mb-8 bg-surface-muted p-1.5 rounded-xl border border-border shadow-inner max-w-lg mx-auto relative z-20">
          <button
            className={`tab-btn ${activeTab === 'swap' ? 'active' : ''}`}
            onClick={() => setActiveTab('swap')}
          >
            <ArrowRightLeft size={18} /> Swap & Pools
          </button>
          <button
            className={`tab-btn ${activeTab === 'vault' ? 'active' : ''}`}
            onClick={() => setActiveTab('vault')}
          >
            <ShieldCheck size={18} /> Rental Vault
          </button>
          <button
            className={`tab-btn ${activeTab === 'gov' ? 'active' : ''}`}
            onClick={() => setActiveTab('gov')}
          >
            <Vote size={18} /> Governance
          </button>
          <button
            className={`tab-btn ${activeTab === 'inventory' ? 'active' : ''}`}
            onClick={() => setActiveTab('inventory')}
          >
            <Layers size={18} /> My Inventory
          </button>
        </div>

        <div className="animate-in fade-in duration-300">
          {activeTab === 'swap' && <SwapTab contracts={currentContracts} />}
          {activeTab === 'vault' && <VaultTab contracts={currentContracts} />}
          {activeTab === 'gov' && <GovernanceTab contracts={currentContracts} />}
          {activeTab === 'inventory' && <InventoryTab itemsData={itemsData} />}
        </div>
      </main>

      <footer className="text-center py-8 text-muted text-sm border-t border-border bg-surface mt-auto">
        <p className="mb-2 font-medium">Built for Ethereum Blockchain Technologies Capstone Suite</p>
        <div className="flex justify-center gap-4 text-xs font-semibold text-accent mt-1">
          <a
            href={activeChainId === 31337 ? "#" : `https://sepolia.arbiscan.io/address/${currentContracts.GameToken}`}
            target="_blank"
            rel="noreferrer"
            className="hover:underline flex items-center gap-1"
          >
            View Token on Arbiscan <ExternalLink size={12} />
          </a>
          <span>•</span>
          <a
            href={activeChainId === 31337 ? "#" : `https://sepolia.arbiscan.io/address/${currentContracts.GameAMM}`}
            target="_blank"
            rel="noreferrer"
            className="hover:underline flex items-center gap-1"
          >
            View AMM on Arbiscan <ExternalLink size={12} />
          </a>
        </div>
      </footer>
    </div>
  );
}

export default function App() {
  return (
    <WagmiProvider config={config}>
      <QueryClientProvider client={queryClient}>
        <AppContent />
      </QueryClientProvider>
    </WagmiProvider>
  );
}
